#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate a complete OpenFOAM-12 MRF case for a propeller STL.

Usage:
    python3 scripts/gen_case.py <caseName> [--rpm 100] [--nprocs 4] \
        [--level 3]

It writes cases/<caseName>/ with blockMesh + snappyHexMesh + topoSet (MRF
cellZone) + the incompressibleFluid (foamRun) steady RANS setup, and copies the
propeller STL (scaled mm->m) into constant/geometry/propeller.stl.

Approach: frozen-rotor MRF (Multiple Reference Frame).  A cylindrical cellZone
"rotor" enclosing the blades is given a rotation rate; the blade surface is a
no-slip wall.  This is steady, robust, and maps directly onto Autodesk CFD's
"rotating region".  Thrust = Z-component of the surface force on patch
"propeller", reported by the forces functionObject.

All lengths in metres.  Air at 20 C: nu = 1.5e-5 m^2/s, rho = 1.225 kg/m^3.
"""
import argparse
import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| OpenFOAM-12  propeller MRF case  (generated by scripts/gen_case.py)          |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    format      ascii;
    class       {cls};
    {loc}object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def head(cls, obj, loc=None):
    locline = 'location    "%s";\n    ' % loc if loc else ""
    return HEADER.format(cls=cls, obj=obj, loc=locline)


# --------------------------------------------------------------------------- #
def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


def gen(case, rpm, nprocs, level, dom):
    cdir = os.path.join(ROOT, "cases", case)
    # ---- domain (metres) ------------------------------------------------- #
    xy = dom["xy"]          # half-width in x,y
    zlo, zhi = dom["zlo"], dom["zhi"]
    nx = dom["nx"]; nz = dom["nz"]
    rotorR = dom["rotorR"]; rotorZ = dom["rotorZ"]

    # =====================================================================  #
    # constant/
    # =====================================================================  #
    write(cdir + "/constant/physicalProperties",
          head("dictionary", "physicalProperties", "constant") +
          "\nviscosityModel  constant;\n\nnu  [0 2 -1 0 0 0 0] 1.5e-05;\n")

    write(cdir + "/constant/momentumTransport",
          head("dictionary", "momentumTransport", "constant") +
          "\nsimulationType  RAS;\n\nRAS\n{\n"
          "    model        kOmegaSST;\n"
          "    turbulence   on;\n"
          "    printCoeffs  on;\n}\n")

    write(cdir + "/constant/MRFProperties",
          head("dictionary", "MRFProperties", "constant") +
          "\nMRF\n{\n"
          "    cellZone    rotor;\n\n"
          "    origin      (0 0 0);\n"
          "    axis        (0 0 1);\n"
          "    omega       %g [rpm];\n}\n" % rpm)

    # =====================================================================  #
    # system/blockMeshDict
    # =====================================================================  #
    bm = head("dictionary", "blockMeshDict", "system") + """
convertToMeters 1;

x0  {xl};  x1  {xh};
y0  {xl};  y1  {xh};
z0  {zlo}; z1  {zhi};

vertices
(
    ($x0 $y0 $z0) ($x1 $y0 $z0) ($x1 $y1 $z0) ($x0 $y1 $z0)
    ($x0 $y0 $z1) ($x1 $y0 $z1) ($x1 $y1 $z1) ($x0 $y1 $z1)
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {nx} {nz}) simpleGrading (1 1 1)
);

defaultPatch {{ name farField; type patch; }}

boundary ();
""".format(xl=-xy, xh=xy, zlo=zlo, zhi=zhi, nx=nx, nz=nz)
    write(cdir + "/system/blockMeshDict", bm)

    # =====================================================================  #
    # system/snappyHexMeshDict
    # =====================================================================  #
    snappy = head("dictionary", "snappyHexMeshDict", "system") + """
castellatedMesh true;
snap            true;
addLayers       false;

geometry
{{
    propeller
    {{
        type triSurfaceMesh;
        file "propeller.stl";
    }}
    rotorRegion
    {{
        type   searchableCylinder;
        point1 (0 0 {rzlo});
        point2 (0 0 {rzhi});
        radius {rR};
    }}
}};

castellatedMeshControls
{{
    maxLocalCells       2000000;
    maxGlobalCells      6000000;
    minRefinementCells  10;
    nCellsBetweenLevels 3;
    maxLoadUnbalance    0.10;
    resolveFeatureAngle 30;
    allowFreeStandingZoneFaces true;

    features
    (
        {{ file "propeller.eMesh"; level {flevel}; }}
    );

    refinementSurfaces
    {{
        propeller
        {{
            level ({slevel} {slevelmax});
            patchInfo {{ type wall; }}
        }}
    }}

    refinementRegions
    {{
        rotorRegion
        {{
            mode   inside;
            levels (({rlevdist} {rlev}));
        }}
    }}

    locationInMesh ({locx} {locy} {locz});
}}

snapControls
{{
    nSmoothPatch     3;
    tolerance        2.0;
    nSolveIter       50;
    nRelaxIter       5;
    nFeatureSnapIter 10;
    implicitFeatureSnap     false;
    explicitFeatureSnap     true;
    multiRegionFeatureSnap  false;
}}

addLayersControls
{{
    relativeSizes       true;
    expansionRatio      1.2;
    finalLayerThickness 0.4;
    minThickness        0.1;
    nGrow               0;
    featureAngle        60;
    nRelaxIter          3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals      3;
    nSmoothThickness    10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedianAxisAngle  90;
    nBufferCellsNoExtrude 0;
    nLayerIter          50;
    layers {{ propeller {{ nSurfaceLayers 3; }} }}
}}

meshQualityControls
{{
    maxNonOrtho         65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave          80;
    minVol              1e-13;
    minTetQuality       1e-15;
    minArea             -1;
    minTwist            0.02;
    minDeterminant      0.001;
    minFaceWeight       0.05;
    minVolRatio         0.01;
    minTriangleTwist    -1;
    nSmoothScale        4;
    errorReduction      0.75;
}}

mergeTolerance 1e-6;
""".format(rzlo=-rotorZ, rzhi=rotorZ, rR=rotorR,
           flevel=level, slevel=level, slevelmax=level,
           rlevdist=2, rlev=max(level - 1, 1),
           locx=0.0, locy=0.0, locz=zhi - 0.02)
    write(cdir + "/system/snappyHexMeshDict", snappy)

    # surfaceFeatures for explicit feature capture
    write(cdir + "/system/surfaceFeaturesDict",
          head("dictionary", "surfaceFeaturesDict", "system") + """
surfaces ("propeller.stl");
includedAngle 150;
""")

    # =====================================================================  #
    # system/topoSetDict  -> MRF cellZone "rotor"
    # =====================================================================  #
    write(cdir + "/system/topoSetDict",
          head("dictionary", "topoSetDict", "system") + """
actions
(
    {{
        name    rotorCells;
        type    cellSet;
        action  new;
        source  cylinderToCell;
        point1  (0 0 {rzlo});
        point2  (0 0 {rzhi});
        radius  {rR};
    }}
    {{
        name    rotor;
        type    cellZoneSet;
        action  new;
        source  setToCellZone;
        set     rotorCells;
    }}
);
""".format(rzlo=-rotorZ, rzhi=rotorZ, rR=rotorR))

    # =====================================================================  #
    # system/controlDict
    # =====================================================================  #
    write(cdir + "/system/controlDict",
          head("dictionary", "controlDict", "system") + """
application     foamRun;
solver          incompressibleFluid;

startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         1500;
deltaT          1;

writeControl    timeStep;
writeInterval   250;
purgeWrite      2;
writeFormat     ascii;
writePrecision  7;
writeCompression off;
timeFormat      general;
runTimeModifiable yes;

functions
{
    #includeFunc forces
}
""")

    # forces functionObject (thrust = forces:z on propeller wall)
    write(cdir + "/system/forces",
          head("dictionary", "forces", "system") + """
type        forces;
libs        ("libforces.so");
patches     (propeller);

rho         rhoInf;
rhoInf      1.225;

CofR        (0 0 0);
writeControl timeStep;
writeInterval 50;
log         yes;
""")

    # =====================================================================  #
    # system/fvSchemes  (steady SIMPLE)
    # =====================================================================  #
    write(cdir + "/system/fvSchemes",
          head("dictionary", "fvSchemes", "system") + """
ddtSchemes      { default steadyState; }

gradSchemes
{
    default         cellLimited Gauss linear 1;
}

divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwindV grad(U);
    div(phi,k)      bounded Gauss upwind;
    div(phi,omega)  bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes { default Gauss linear limited corrected 0.33; }
interpolationSchemes { default linear; }
snGradSchemes   { default limited corrected 0.33; }
wallDist        { method meshWave; }
""")

    # =====================================================================  #
    # system/fvSolution
    # =====================================================================  #
    write(cdir + "/system/fvSolution",
          head("dictionary", "fvSolution", "system") + """
solvers
{
    p
    {
        solver          GAMG;
        smoother        GaussSeidel;
        tolerance       1e-7;
        relTol          0.01;
    }
    "(U|k|omega)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }
}

SIMPLE
{
    nNonOrthogonalCorrectors 1;
    consistent      yes;
    residualControl
    {
        p     1e-4;
        U     1e-4;
        "(k|omega)" 1e-4;
    }
}

relaxationFactors
{
    equations
    {
        U       0.9;
        ".*"    0.7;
    }
}
""")

    # =====================================================================  #
    # system/decomposeParDict
    # =====================================================================  #
    write(cdir + "/system/decomposeParDict",
          head("dictionary", "decomposeParDict", "system") + """
numberOfSubdomains %d;
method          scotch;
""" % nprocs)

    # =====================================================================  #
    # 0/  fields
    # =====================================================================  #
    Uinf = "(0 0 0)"
    k0 = 0.01      # small freestream turbulence (hover, quiescent air)
    omega0 = 1.0
    nut0 = 0.0

    write(cdir + "/0/U",
          head("volVectorField", "U", "0") + """
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform {U};

boundaryField
{{
    farField
    {{
        type            pressureInletOutletVelocity;
        value           uniform {U};
    }}
    propeller
    {{
        type            noSlip;
    }}
}}
""".format(U=Uinf))

    write(cdir + "/0/p",
          head("volScalarField", "p", "0") + """
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform 0;

boundaryField
{
    farField
    {
        type            totalPressure;
        p0              uniform 0;
    }
    propeller
    {
        type            zeroGradient;
    }
}
""")

    write(cdir + "/0/k",
          head("volScalarField", "k", "0") + """
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform {k};

boundaryField
{{
    farField
    {{
        type            inletOutlet;
        inletValue      uniform {k};
        value           uniform {k};
    }}
    propeller
    {{
        type            kqRWallFunction;
        value           uniform {k};
    }}
}}
""".format(k=k0))

    write(cdir + "/0/omega",
          head("volScalarField", "omega", "0") + """
dimensions      [0 0 -1 0 0 0 0];
internalField   uniform {w};

boundaryField
{{
    farField
    {{
        type            inletOutlet;
        inletValue      uniform {w};
        value           uniform {w};
    }}
    propeller
    {{
        type            omegaWallFunction;
        value           uniform {w};
    }}
}}
""".format(w=omega0))

    write(cdir + "/0/nut",
          head("volScalarField", "nut", "0") + """
dimensions      [0 2 -1 0 0 0 0];
internalField   uniform {n};

boundaryField
{{
    farField    {{ type calculated; value uniform {n}; }}
    propeller   {{ type nutkWallFunction; value uniform {n}; }}
}}
""".format(n=nut0))

    # ---- copy / scale STL ------------------------------------------------ #
    src_stl = os.path.join(ROOT, "geometry", case, case + ".stl")
    dst_stl = os.path.join(cdir, "constant", "geometry", "propeller_mm.stl")
    os.makedirs(os.path.dirname(dst_stl), exist_ok=True)
    if os.path.exists(src_stl):
        shutil.copy(src_stl, dst_stl)   # kept in mm; Allrun scales -> propeller.stl

    # =====================================================================  #
    # Allrun / Allclean
    # =====================================================================  #
    allrun = """#!/bin/sh
cd "${{0%/*}}" || exit 1
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# STL exported from FreeCAD is in mm -> scale to metres (idempotent: src kept)
runApplication surfaceTransformPoints "scale=(0.001 0.001 0.001)" \\
    constant/geometry/propeller_mm.stl constant/geometry/propeller.stl

runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite
runApplication topoSet

runApplication decomposePar
runParallel foamRun
runApplication reconstructPar -latestTime

# thrust (Z-force) history is in postProcessing/forces/*/force.dat
echo "Done.  Thrust = Z-component of total force on patch 'propeller'."
"""
    write(cdir + "/Allrun", allrun)
    os.chmod(cdir + "/Allrun", 0o755)

    allclean = """#!/bin/sh
cd "${0%/*}" || exit 1
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"
cleanCase
rm -rf processor* postProcessing
"""
    write(cdir + "/Allclean", allclean)
    os.chmod(cdir + "/Allclean", 0o755)

    print("generated case:", cdir)
    print("  rpm=%g nprocs=%d refinement level=%d" % (rpm, nprocs, level))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("case")
    ap.add_argument("--rpm", type=float, default=100.0)
    ap.add_argument("--nprocs", type=int, default=4)
    ap.add_argument("--level", type=int, default=3)
    a = ap.parse_args()

    # domain in metres: box +-0.18 in x,y, z from -0.30..0.30
    # nx=48 -> ~7.5 mm background cells; surface refinement adds resolution
    dom = dict(xy=0.18, zlo=-0.30, zhi=0.30, nx=48, nz=80,
               rotorR=0.056, rotorZ=0.035)
    gen(a.case, a.rpm, a.nprocs, a.level, dom)


if __name__ == "__main__":
    main()
